name: Deploy Website

on:
  push:
    branches:
      - master # Trigger when changes are pushed to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Gets repository files

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch where GitHub Pages serves the site
          folder: . # Deploy everything in the repository root
